const app=document.getElementById('app');
const SAMPLE={recipient:'NorthLane Marketplace (fictional sample recipient)',purpose:'Age gate before checkout',request:'Confirm this person is 18 or older. Please provide a government licence showing name, date of birth and home address.'};
const CATS=[
{id:'age',label:'Age eligibility',field:'age_eligibility',kind:'narrow_fact',why:'A yes/no age threshold can avoid exposing an exact birth date.',re:/age|18|adult|birth|dob/i},
{id:'name',label:'Legal name',field:'legal_name',kind:'raw_data',why:'A full legal name may identify you beyond the stated purpose.',re:/name|identity|licen[cs]e|passport/i},
{id:'dob',label:'Date of birth',field:'date_of_birth',kind:'raw_data',why:'Exact birth date is more information than an age threshold.',re:/birth|dob|age|licen[cs]e|passport/i},
{id:'address',label:'Home address',field:'home_address',kind:'raw_data',why:'Your home address can reveal where you live when that may not be necessary.',re:/address|residen|home|licen[cs]e/i},
{id:'id',label:'Government ID',field:'government_id',kind:'raw_data',why:'An ID document can expose multiple unrelated fields at once.',re:/government|licen[cs]e|passport|photo id|identification/i},
{id:'income',label:'Income details',field:'income_details',kind:'raw_data',why:'Raw financial records can reveal more than a threshold or eligibility fact.',re:/income|salary|pay|earn|bank/i},
{id:'phone',label:'Phone number',field:'phone_number',kind:'raw_data',why:'A phone number creates a persistent contact identifier.',re:/phone|mobile|telephone/i},
{id:'email',label:'Email address',field:'email_address',kind:'raw_data',why:'An email address can identify and track you across services.',re:/email|e-mail/i}
];
let state={screen:'intro',intro:0,draft:{recipient:'',purpose:'',request:''},sample:false,detected:[],minimum:[],receipt:null,error:''};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cat=id=>CATS.find(c=>c.id===id);
function btn(text,action,cls=''){return `<button class="btn ${cls}" data-action="${action}">${text}</button>`}
function shell(title,caption,body){return `<div class="stepbar">${state.screen!=='intro'?btn('← Back','back'):''}<span>${esc(caption)}</span>${state.sample?'<span class="tag">Sample — fictional</span>':''}${state.screen!=='intro'?'<button class="btn clear" data-action="clear">Clear session</button>':''}</div><section class="panel"><div class="eyebrow">${esc(caption)}</div><h2 style="font-size:34px;font-weight:400;margin:8px 0 26px">${esc(title)}</h2>${body}</section>`}
function render(){
 if(state.screen==='intro') return renderIntro();
 if(state.screen==='request') return renderRequest();
 if(state.screen==='inspect') return renderInspect();
 if(state.screen==='margin') return renderMargin();
 if(state.screen==='prepared') return renderPrepared();
 if(state.screen==='receipt') return renderReceipt();
}
function renderIntro(){const steps=[['Connect','A request arrives. See what is being asked before you answer.'],['Prove','Separate the narrow fact from the raw record behind it.'],['Share','Prepare the minimum and keep a metadata-only receipt.']]; if(state.intro<3){const s=steps[state.intro];app.innerHTML=`<section class="panel introcard"><div class="lens" style="width:125px;height:125px"></div><div class="stage">0${state.intro+1} / ${s[0]}</div><h1 style="font-size:42px">${s[0]}</h1><p class="lede" style="font-size:18px">${s[1]}</p><div class="actions">${btn('Continue →','nextIntro','primary')}</div></section>`}else{app.innerHTML=`<section class="panel introcard"><div class="lens" style="width:135px;height:135px"></div><div class="eyebrow">Live demo — runs locally in your browser</div><h1 style="font-size:44px">Private until you connect</h1><p class="lede" style="font-size:18px">Describe a request, inspect it, pause at The Margin, then prepare the minimum. Nothing is transmitted by this browser demo.</p><div class="actions">${btn('Connect a request →','custom','primary')}${btn('Open fictional sample','sample')}</div></section>`}bind()}
function renderRequest(){app.innerHTML=shell('Request','Step 1 — describe what is being asked of you',`<div class="form"><div class="field"><label>Who is asking?</label><div class="hint">Company, app, agent, or person making the request.</div><input id="recipient" value="${esc(state.draft.recipient)}" placeholder="e.g. Acme Rentals"></div><div class="field"><label>What is the stated purpose?</label><div class="hint">Why they say they need it.</div><input id="purpose" value="${esc(state.draft.purpose)}" placeholder="e.g. Tenancy application check"></div><div class="field"><label>What are they requesting, in plain English?</label><div class="hint">Do not paste personal values, numbers, dates, addresses or documents.</div><textarea id="request" placeholder="e.g. They want proof I earn over a threshold and a copy of my passport.">${esc(state.draft.request)}</textarea></div><div class="notice">Everything you type stays in this browser tab for this session. The demo does not upload your request.</div>${state.error?`<div class="notice error">${esc(state.error)}</div>`:''}<div class="actions" style="justify-content:flex-start">${btn('Inspect this request →','inspect','primary')}${btn('Use fictional sample','sample')}</div></div>`); bind();}
function detect(){return CATS.filter(c=>c.re.test(state.draft.request)).map(c=>c.id)}
function renderInspect(){let items=state.detected.map(id=>{const c=cat(id),on=state.minimum.includes(id);return `<div class="cat"><div><strong>${esc(c.label)}</strong> <span class="tag">${c.kind==='narrow_fact'?'Narrow fact':'Raw data'}</span><small>${esc(c.field)}</small><p>${esc(c.why)}</p></div>${btn(on?'✓ Necessary':'Mark necessary',`toggle:${id}`,on?'primary':'')}</div>`}).join(''); const add=CATS.filter(c=>!state.detected.includes(c.id)).map(c=>btn('+ '+c.label,`add:${c.id}`)).join(' '); app.innerHTML=shell('Interpret & inspect','Step 2 — what this request would typically reach for',`<div class="panel" style="padding:16px;margin-bottom:18px"><div class="row"><dt>Recipient</dt><dd>${esc(state.draft.recipient)}</dd></div><div class="row"><dt>Purpose</dt><dd>${esc(state.draft.purpose)}</dd></div><div class="row"><dt>Request</dt><dd>${esc(state.draft.request)}</dd></div></div><div class="notice">Detected locally with simple keyword matching. Nothing is preselected. You decide what is necessary.</div><div style="margin-top:18px">${items||'<p class="muted">No sensitive categories matched automatically. Add one below if applicable.</p>'}</div><details class="panel" style="padding:16px;margin-top:16px"><summary>Add a category Lens did not catch</summary><div class="actions" style="justify-content:flex-start">${add}</div></details><div class="actions" style="justify-content:flex-start">${btn('Continue to The Margin →','margin','primary')}${btn('Edit request','back')}</div>`); bind();}
function renderMargin(){const withheld=state.detected.filter(x=>!state.minimum.includes(x));const list=ids=>ids.length?ids.map(id=>`<div class="pre" style="padding:8px 10px;margin-top:7px">${esc(cat(id).field)}</div>`).join(''):'<p class="muted">None</p>'; app.innerHTML=shell('The Margin','Step 3 — the pause before you choose what to share',`<div class="notice">Nothing has been prepared or sent yet.</div><div class="split" style="margin-top:18px"><div class="box good"><div class="eyebrow">Approved to share</div>${list(state.minimum)}</div><div class="box bluebox"><div class="eyebrow">Withheld</div>${list(withheld)}</div></div>${state.error?`<div class="notice error" style="margin-top:16px">${esc(state.error)}</div>`:''}<div class="actions" style="justify-content:flex-start">${btn('Prepare the minimum →','prepare','primary')}${btn('Adjust selection','back')}${btn('Decline request','decline','danger')}</div>`); bind();}
async function makeReceipt(decision){const withheld=state.detected.filter(x=>!state.minimum.includes(x));const payload={schema:'midnight-lens.receipt/1.0',issued_at_utc:new Date().toISOString(),recipient:state.draft.recipient,purpose:state.draft.purpose,decision,source:state.sample?'sample_scenario':'custom_request',shared_fields:(decision==='approved_minimum'?state.minimum:[]).map(id=>cat(id).field),withheld_fields:(decision==='approved_minimum'?withheld:state.detected).map(id=>cat(id).field),data_handling:'Metadata only. Personal values are not stored in this receipt.'}; const raw=new TextEncoder().encode(JSON.stringify(payload)); const hash=await crypto.subtle.digest('SHA-256',raw); payload.receipt_id='lens-'+Array.from(new Uint8Array(hash)).slice(0,8).map(b=>b.toString(16).padStart(2,'0')).join(''); payload.integrity={algorithm:'SHA-256',fingerprint:Array.from(new Uint8Array(hash)).map(b=>b.toString(16).padStart(2,'0')).join('')}; return payload}
function outbound(){const withheld=state.detected.filter(x=>!state.minimum.includes(x));return JSON.stringify({schema:'midnight-lens.disclosure/1.0',recipient:state.draft.recipient,purpose:state.draft.purpose,prepared_locally:true,shared_fields:state.minimum.map(id=>cat(id).field),withheld_fields:withheld.map(id=>cat(id).field),note:'Field names only. No personal values are included. Prepared locally and not sent by Midnight Lens.'},null,2)}
function renderPrepared(){app.innerHTML=shell('Prepared response','Step 4 — prepared locally, not sent',`<p class="muted" style="line-height:1.7">This minimum-disclosure response was prepared locally. It has <strong style="color:var(--text)">not been sent</strong> to the recipient or any third party. It contains field names only.</p><pre class="pre" id="outbound">${esc(outbound())}</pre><div class="actions" style="justify-content:flex-start">${btn('Copy response','copy','primary')}${btn('Download response','download')}${btn('Privacy receipt →','receipt')}</div>`); bind();}
function renderReceipt(){const r=state.receipt;const rows=[['Schema',r.schema],['Issued (UTC)',r.issued_at_utc],['Recipient',r.recipient],['Purpose',r.purpose],['Decision',r.decision],['Shared field names',r.shared_fields.join(', ')||'None'],['Withheld field names',r.withheld_fields.join(', ')||'None']].map(([a,b])=>`<div class="row"><dt>${esc(a)}</dt><dd>${esc(b)}</dd></div>`).join(''); app.innerHTML=shell('Privacy receipt','Step 5 — metadata only, kept by you',`<div class="panel" style="padding:16px">${rows}<div style="margin-top:18px"><div class="eyebrow">SHA-256 fingerprint</div><div class="pre" style="margin-top:8px">${esc(r.integrity.fingerprint)}</div></div></div><div class="actions" style="justify-content:flex-start">${btn('Download JSON','receiptDownload','primary')}${btn('Clear session','clear')}</div>`); bind();}
function download(name,text,type='application/json'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function bind(){document.querySelectorAll('[data-action]').forEach(el=>el.onclick=async()=>{const a=el.dataset.action;if(a==='nextIntro'){state.intro++;return render()}if(a==='custom'){state={...state,screen:'request',sample:false,draft:{recipient:'',purpose:'',request:''},detected:[],minimum:[],receipt:null,error:''};return render()}if(a==='sample'){state={...state,screen:'request',sample:true,draft:{...SAMPLE},detected:[],minimum:[],receipt:null,error:''};return render()}if(a==='inspect'){state.draft={recipient:document.getElementById('recipient').value.trim(),purpose:document.getElementById('purpose').value.trim(),request:document.getElementById('request').value.trim()};if(!state.draft.recipient||!state.draft.purpose||state.draft.request.length<8){state.error='Add a recipient, a purpose, and a short description of what is being requested.';return render()}state.detected=detect();state.minimum=[];state.error='';state.screen='inspect';return render()}if(a.startsWith('toggle:')){const id=a.split(':')[1];state.minimum=state.minimum.includes(id)?state.minimum.filter(x=>x!==id):[...state.minimum,id];return render()}if(a.startsWith('add:')){state.detected.push(a.split(':')[1]);return render()}if(a==='margin'){state.screen='margin';return render()}if(a==='prepare'){if(!state.minimum.length){state.error='Mark at least one item necessary, or decline the request.';return render()}state.receipt=await makeReceipt('approved_minimum');state.screen='prepared';return render()}if(a==='decline'){state.receipt=await makeReceipt('declined');state.screen='receipt';return render()}if(a==='receipt'){state.screen='receipt';return render()}if(a==='copy'){await navigator.clipboard.writeText(outbound());el.textContent='Copied';return}if(a==='download'){return download('midnight-lens-minimum-disclosure.json',outbound())}if(a==='receiptDownload'){return download('midnight-lens-privacy-receipt.json',JSON.stringify(state.receipt,null,2))}if(a==='clear'){state={screen:'intro',intro:0,draft:{recipient:'',purpose:'',request:''},sample:false,detected:[],minimum:[],receipt:null,error:''};return render()}if(a==='back'){if(state.screen==='request'){state.screen='intro';state.intro=3}else if(state.screen==='inspect')state.screen='request';else if(state.screen==='margin')state.screen='inspect';else if(state.screen==='prepared')state.screen='margin';else if(state.screen==='receipt')state.screen=state.receipt?.decision==='declined'?'margin':'prepared';return render()}})}
render();